import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.doctors': 'Doctors',
    'nav.howItWorks': 'How it works',
    'nav.howVerificationWorks': 'How verification works',
    'nav.forDoctors': 'For Doctors',
    'nav.about': 'About',
    'nav.users': 'Users',
    'nav.dashboard': 'Dashboard',
    // Auth
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign up',
        // Hero
        'hero.title': 'Your safe space',
        'hero.titleAccent': 'for balance and peace.',
        'hero.subtitle': 'At Sabina, we believe that seeking support is a brave step toward a more balanced life. We connect you with elite licensed psychologists to help you overcome challenges in an environment characterized by complete privacy and deep understanding, free from any judgment.',
        'hero.badge': 'Trusted Mental Health Network',
        'hero.sessions': 'Verified Sessions',
        'hero.findSupport': 'Find Support Now',
        'hero.howProtect': 'How we protect you',
        'hero.trustPills.verified': 'Verified doctors',
        'hero.trustPills.privacy': 'Privacy-first',
        'hero.trustPills.pricing': 'Transparent pricing',
        // Search
        'search.specialty': 'Expertise',
        'search.location': 'Your Location',
        'search.placeholder': 'What do you need help with?',
        'search.button': 'Find Doctors',
        // Categories
        'cat.anxiety': 'Anxiety',
        'cat.depression': 'Depression',
        'cat.couples': 'Couples',
        'cat.trauma': 'Trauma',
        'cat.adhd': 'ADHD',
        'cat.stress': 'Stress',
        // Home Sections
        'home.featuredTitle': 'Featured Professionals',
        'home.featuredSubtitle': 'Hand-picked, highly-rated specialists ready to support your journey.',
        'home.howTitle': 'How Sabina works',
        'home.howSubtitle': 'A simple, step-by-step journey designed to help users feel informed, safe, and ready to book.',
        // About Page
        'about.heroTitle': 'Your safe space',
        'about.heroTitleAccent': 'for balance and peace.',
        'about.heroSubtitle': 'Because your mental health is the beginning of everything beautiful in your life.',
        'about.commitmentTitle': 'About Sabina Therapy',
        'about.commitmentSubtitle': 'Sabina is a modern digital platform born from the belief that mental health care is a right for everyone. We are not just a directory of specialists, but your companion on the journey of searching for the best and most peaceful version of yourself.',
        'about.missionTitle': 'Our Mission',
        'about.missionSubtitle': 'Empowering individuals, couples, and youth in the Arab world to access professional mental health support that transcends geographical and social barriers, spreading the culture of psychological awareness as a fundamental pillar of quality of life.',
        'about.whyLifeTitle': 'Why does your mental health matter?',
        'about.whyLifeSubtitle': 'Because facing anxiety, stress, or life pressures is not a journey you should go through alone. Mental health is the engine that gives us the ability to give, create, and build healthy and sustainable relationships.',
        'about.promisesTitle': 'Why choose Sabina?',
        'about.promise1': 'Absolute privacy and confidentiality with advanced security standards.',
        'about.promise2': 'Elite licensed specialists verified for professional reliability.',
        'about.promise3': 'Ease and flexibility in booking from anywhere, at any time.',
        'about.promise4': 'Specialized and diverse support for individuals, couples, and youth.',
        'about.promise5': 'Judgment-free environment with emotionally intelligent therapists.',
        'about.howStep1Title': 'Search',
        'about.howStep1Desc': 'Find psychologists by specialty, city, language, and online availability.',
        'about.howStep2Title': 'Compare',
        'about.howStep2Desc': 'Review profile details, pricing, and ratings to choose with confidence.',
        'about.howStep3Title': 'Book',
        'about.howStep3Desc': 'Pick online or in-person sessions and confirm your appointment.',
        'about.howStep4Title': 'Follow up',
        'about.howStep4Desc': 'Manage upcoming sessions and contact support if you need assistance.',
        'about.impactTitle': 'Our Collective Impact',
        'about.impactSubtitle': 'A quick snapshot of the growing Sabina community and our shared progress.',
        'about.impactLabel1': 'Licensed Professionals',
        'about.impactLabel2': 'Moments of Connection',
        'about.impactLabel3': 'Average Support Rating',
        'about.impactLabel4': 'Always Here For You',
        'about.founderBadge': 'Platform Founder',
        'about.founderEducation': 'Education',
        'about.founderCareer': 'Career Highlights',
        'about.founderExperience': 'Clinical Experience',
        'about.founderSpecializations': 'Primary Specializations',
        'about.whyTitle': 'Why Sabina?',
        'about.treatmentTitle': 'What You Get From Treatment',
        'about.credentialsTitle': 'Professional Credentials',
        'about.credentialsBoard': 'Board Certification',
        'about.credentialsTimeline': 'Practice Timeline',
        'about.credentialsLanguages': 'Languages',
        'about.focusTitle': 'Areas of Focus & Expertise',
        'about.mediaTitle': 'Recognition & Media Appearances',
        'about.mediaDesc': 'Dr. Mizher has been featured in leading regional publications, sharing clinical insights on mental health, addiction recovery, and the psychological impact of contemporary challenges.',
        'about.safetyTitle': 'Your safety is our priority',
        'about.safetySubtitle': 'Trust is built through empathy, careful clinical review, and transparent platform behavior. We protect you so you can focus on healing.',
        'about.safetyItem1Title': 'Doctor verification',
        'about.safetyItem1Desc': 'Applications are reviewed by admins and credentials are checked before approval.',
        'about.safetyItem2Title': 'Privacy-first approach',
        'about.safetyItem2Desc': 'We aim to collect only what is needed for booking and use reasonable safeguards for handling data.',
        'about.safetyItem3Title': 'Clear pricing & details',
        'about.safetyItem3Desc': 'Session pricing, duration, and mode are displayed so users can compare transparently.',
        'about.safetyItem4Title': 'Reporting and reviews',
        'about.safetyItem4Desc': 'Ratings, feedback, and reporting tools help us maintain quality and community trust.',
        'about.faqTitle': 'Frequently asked questions',
        'about.faqSubtitle': 'Quick answers to common questions from users and doctors.',
        'faq.q1': 'Are sessions on Sabina confidential?',
        'faq.a1': 'Absolutely. Privacy is the cornerstone of our platform. We use advanced encryption technologies to ensure that everything that happens in the session remains only between you and your therapist.',
        'faq.q2': 'How do I choose the right therapist for me?',
        'faq.a2': 'You can browse therapists\' profiles, view their specialties, years of experience, and therapeutic approach to choose the one you feel most comfortable with.',
        'faq.q3': 'Can I cancel or change my session time?',
        'faq.a3': 'Yes, we understand that plans change. You can reschedule or cancel your session easily via your dashboard according to our flexible cancellation policy.',
        'faq.q4': 'What is the difference between individual and couples therapy?',
        'faq.a4': 'Individual therapy focuses on your personal growth and dealing with your own feelings, while couples therapy aims to improve communication, resolve conflicts, and build a stronger, more understanding relationship.',
        'about.ctaTitle': 'Start your journey toward inner peace today',
        'about.ctaSubtitle': 'You deserve to feel better. Our team of specialists is ready to listen and share the first step with you.',
        'about.ctaFind': 'Find a doctor',
        'about.ctaApply': 'Apply as a doctor',
        'doctor.forDoctorsTitle': 'Join the Sabina Professional Community',
        'doctor.forDoctorsSubtitle': 'Are you a licensed therapist seeking to make a real difference? Join Sabina Therapy to expand your professional reach and provide your expertise to those who need it in an advanced digital environment. We provide you with the platform that enhances your presence, and gives you the tools to manage your sessions with flexibility and professionalism, with full focus on the quality of care you provide.',
        // Doctor Card/Profile
        'doctor.verified': 'Verified',
        'doctor.responds': 'Usually responds within 2 hours',
        'doctor.price': 'Price',
        'doctor.priceSuffix': ' / session',
        'doctor.session': 'Session length',
        'doctor.available': 'Next available',
        'doctor.book': 'Book appointment',
        'doctor.viewProfile': 'View profile',
        'doctor.message': 'Message doctor',
        'doctor.secure': 'Secure payment • Cancel up to 24h before',
        'profile.about': 'About',
        'profile.services': 'Services',
        'profile.availability': 'Availability',
        'profile.reviews': 'Reviews',
        'profile.methodology': 'My Methodology',
        'profile.experience': 'Professional Experience',
        'profile.education': 'Academic Background',
        'profile.insurance': 'Insurance & Coverage',
        'profile.insuranceDesc': 'Dr. Sara is a verified partner with leading providers.',
        'profile.specializations': 'Clinical Specializations',
        'profile.watchIntro': 'Watch Introduction',
        'booking.quick': 'Quick booking',
        'booking.service': 'Service',
        'booking.date': 'Date',
        'booking.time': 'Time slots',
        'booking.continue': 'Continue to booking',
            'booking.similar': 'Similar doctors',
            'footer.rights': '© 2026 Sabina Therapy. All rights reserved.',
            'search.consultationType': 'Consultation Type',
            'search.clinic': 'Clinic Visit',
            'search.online': 'Online Session',
            'search.home': 'Home Visit',
            'search.mainPlaceholder': 'Search therapist, specialty, or concern like anxiety/depression',
            'search.specialtyPlaceholder': 'Specialization',
            'search.concernPlaceholder': 'Concern / Symptom',
            'search.approachPlaceholder': 'Therapy approach',
            'search.languagePlaceholder': 'Language',
            'search.sessionTypePlaceholder': 'Session type',
            'search.locationPlaceholder': 'Location or online',
            'search.genderPlaceholder': 'Therapist gender',
            'search.insurancePlaceholder': 'Insurance provider',
            'search.availabilityPlaceholder': 'Availability',
            'search.minPricePlaceholder': 'Min price',
            'search.maxPricePlaceholder': 'Max price',
            'search.resetFilters': 'Reset filters',
            'search.doctorNamePlaceholder': 'Search by doctor name...',
            'founder.readMore': 'Read Full Founder Story',
            'home.dataUnavailable': 'Live data is temporarily unavailable. Showing demo doctors.',
          },
          ar: {
            // Nav
            'nav.home': 'الرئيسية',
            'nav.doctors': 'الأطباء',
            'nav.howItWorks': 'كيف يعمل',
            'nav.howVerificationWorks': 'كيف تعمل المصادقة',
            'nav.forDoctors': 'للأطباء',
            'nav.about': 'حول',
            'nav.users': 'المستخدمين',
            'nav.dashboard': 'لوحة التحكم',
            // Auth
            'auth.signIn': 'دخول',
            'auth.signUp': 'اشترك',
            // Hero
            'hero.title': 'مساحتك الآمنة',
            'hero.titleAccent': 'للتوازن النفسي والهدوء.',
            'hero.subtitle': 'في "صابينا"، نؤمن أن طلب الدعم هو خطوة شجاعة نحو حياة أكثر اتزاناً. نصلك بنخبة من المختصين النفسيين المرخصين لمساعدتك على تجاوز التحديات في بيئة تتسم بالخصوصية التامة والتفهم العميق، بعيداً عن أي أحكام.',
            'hero.badge': 'شبكة الصحة النفسية الموثوقة',
            'hero.sessions': 'جلسة معتمدة',
            'hero.findSupport': 'ابحث عن الدعم الآن',
            'hero.howProtect': 'كيف نحميك',
            'hero.trustPills.verified': 'أطباء معتمدون',
            'hero.trustPills.privacy': 'الخصوصية أولاً',
            'hero.trustPills.pricing': 'أسعار شفافة',
            // Search
            'search.specialty': 'التخصص',
            'search.location': 'موقعك',
            'search.placeholder': 'بماذا يمكننا مساعدتك؟',
            'search.button': 'ابحث عن طبيب',
            'search.consultationType': 'نوع الاستشارة',
            'search.clinic': 'استشارة عيادة',
            'search.online': 'استشارة أونلاين',
            'search.home': 'زيارة منزلية',
            'search.mainPlaceholder': 'ابحث عن معالج نفسي، تخصص، أو مشكلة مثل القلق والاكتئاب',
            'search.specialtyPlaceholder': 'التخصص',
            'search.concernPlaceholder': 'المشكلة أو الأعراض',
            'search.approachPlaceholder': 'المنهج العلاجي',
            'search.languagePlaceholder': 'اللغة',
            'search.sessionTypePlaceholder': 'نوع الجلسة',
            'search.locationPlaceholder': 'الموقع أو أونلاين',
            'search.genderPlaceholder': 'جنس المعالج',
            'search.insurancePlaceholder': 'مزود التأمين',
            'search.availabilityPlaceholder': 'أقرب موعد متاح',
            'search.minPricePlaceholder': 'أقل سعر',
            'search.maxPricePlaceholder': 'أعلى سعر',
            'search.resetFilters': 'إعادة تعيين الفلاتر',
            'search.doctorNamePlaceholder': 'ابحث باسم الدكتور...',
            'founder.readMore': 'اقرأ المزيد عن المؤسس',
            'home.dataUnavailable': 'بيانات البث المباشر غير متوفرة مؤقتاً. عرض الأطباء التجريبيين.',
            // Categories
            'cat.anxiety': 'القلق',
        'cat.depression': 'الاكتئاب',
        'cat.couples': 'الأزواج',
        'cat.trauma': 'الصدمات',
        'cat.adhd': 'تشتت الانتباه',
        'cat.stress': 'الضغوط',
        // Home Sections
        'home.featuredTitle': 'متخصصون متميزون',
        'home.featuredSubtitle': 'متخصصون مختارون بعناية وحاصلون على تقييمات عالية مستعدون لدعم رحلتك.',
        'home.howTitle': 'كيف يعمل Sabina',
        'home.howSubtitle': 'رحلة بسيطة خطوة بخطوة مصممة لمساعدة المستخدمين على الشعور بالاطلاع والأمان والاستعداد للحجز.',
        // About Page
        'about.heroTitle': 'مساحتك الآمنة',
        'about.heroTitleAccent': 'للتوازن النفسي والهدوء',
        'about.heroSubtitle': 'لأن صحتك النفسية هي البداية لكل شيء جميل في حياتك.',
        'about.commitmentTitle': 'عن صابينا ثيرابي',
        'about.commitmentSubtitle': 'صابينا هي منصة رقمية حديثة ولدت من الإيمان بأن الرعاية النفسية حق للجميع. نحن لسنا مجرد دليل للمختصين، بل نحن رفيقك في رحلة البحث عن النسخة الأفضل والأكثر سلاماً من ذاتك.',
        'about.missionTitle': 'رسالتنا',
        'about.missionSubtitle': 'تمكين الأفراد والأزواج والشباب في العالم العربي من الوصول إلى دعم نفسي احترافى يتخطى العوائق الجغرافية والاجتماعية، لنشر ثقافة الوعي النفسي كركيزة أساسية لجودة الحياة.',
        'about.whyLifeTitle': 'لماذا تهمنا صحتك النفسية؟',
        'about.whyLifeSubtitle': 'لأن مواجهة القلق، التوتر، أو ضغوطات الحياة ليست رحلة يجب أن تخوضها بمفردك. الصحة النفسية هي المحرك الذي يمنحنا القدرة على العطاء، الإبداع، وبناء علاقات صحية ومستدامة.',
        'about.promisesTitle': 'لماذا صابينا؟',
        'about.promise1': 'خصوصية وسرية مطلقة مع اعتماد أعلى معايير الأمان.',
        'about.promise2': 'نخبة من المختصين المرخصين والمتحقق من كفاءتهم المهنية.',
        'about.promise3': 'سهولة ومرونة في الحجز من أي مكان وفي أي وقت.',
        'about.promise4': 'دعم متخصص ومتنوع للأفراد، الأزواج، والشباب.',
        'about.promise5': 'بيئة خالية من الأحكام مع معالجين يتمتعون بالذكاء العاطفي.',
        'about.howStep1Title': 'البحث',
        'about.howStep1Desc': 'ابحث عن أخصائيين نفسيين حسب التخصص والمدينة واللغة والتوافر عبر الإنترنت.',
        'about.howStep2Title': 'المقارنة',
        'about.howStep2Desc': 'راجع تفاصيل الملف الشخصي والأسعار والتقييمات للاختيار بثقة.',
        'about.howStep3Title': 'الحجز',
        'about.howStep3Desc': 'اختر جلسات عبر الإنترنت أو شخصية وأكد موعدك.',
        'about.howStep4Title': 'المتابعة',
        'about.howStep4Desc': 'إدارة الجلسات القادمة والتواصل مع الدعم إذا كنت بحاجة إلى مساعدة.',
        'about.impactTitle': 'تأثيرنا الجماعي',
        'about.impactSubtitle': 'لقطة سريعة لمجتمع Sabina المتنامي وتقدمنا المشترك.',
        'about.impactLabel1': 'أخصائيون مرخصون',
        'about.impactLabel2': 'لحظات تواصل',
        'about.impactLabel3': 'متوسط تقييم الدعم',
        'about.impactLabel4': 'دائماً هنا من أجلك',
        'about.founderBadge': 'مؤسس المنصة',
        'about.founderEducation': 'التعليم',
        'about.founderCareer': 'أبرز المحطات المهنية',
        'about.founderExperience': 'الخبرة السريرية',
        'about.founderSpecializations': 'التخصصات الأساسية',
        'about.whyTitle': 'لماذا Sabina؟',
        'about.treatmentTitle': 'ما تحصل عليه من العلاج',
        'about.credentialsTitle': 'الاعتمادات المهنية',
        'about.credentialsBoard': 'شهادة البورد',
        'about.credentialsTimeline': 'الجدول الزمني للممارسة',
        'about.credentialsLanguages': 'اللغات',
        'about.focusTitle': 'مجالات التركيز والخبرة',
        'about.mediaTitle': 'الظهور الإعلامي والتقدير',
        'about.mediaDesc': 'ظهر الدكتور مزهر في منشورات إقليمية رائدة، حيث شارك رؤى سريرية حول الصحة النفسية والتعافي من الإدمان والتأثير النفسي للتحديات المعاصرة.',
        'about.safetyTitle': 'سلامتك هي أولويتنا',
        'about.safetySubtitle': 'تُبنى الثقة من خلال التعاطف والمراجعة السريرية الدقيقة وسلوك المنصة الشفاف. نحن نحميك حتى تتمكن من التركيز على الشفاء.',
        'about.safetyItem1Title': 'التحقق من الطبيب',
        'about.safetyItem1Desc': 'تتم مراجعة الطلبات من قبل المسؤولين ويتم التحقق من الاعتمادات قبل الموافقة.',
        'about.safetyItem2Title': 'نهج الخصوصية أولاً',
        'about.safetyItem2Desc': 'نهدف إلى جمع ما هو مطلوب فقط للحجز واستخدام ضمانات معقولة للتعامل مع البيانات.',
        'about.safetyItem3Title': 'أسعار وتفاصيل واضحة',
        'about.safetyItem3Desc': 'يتم عرض أسعار الجلسات ومدتها ووضعها حتى يتمكن المستخدمون من المقارنة بشفافية.',
        'about.safetyItem4Title': 'التقارير والتقييمات',
        'about.safetyItem4Desc': 'تساعدنا التقييمات والملاحظات وأدوات الإبلاغ في الحفاظ على الجودة وثقة المجتمع.',
        'about.faqTitle': 'الأسئلة الشائعة',
        'about.faqSubtitle': 'إجابات سريعة على الأسئلة الشائعة من المستخدمين والأطباء.',
        'faq.q1': 'هل الجلسات في "صابينا" سرية؟',
        'faq.a1': 'بكل تأكيد. الخصوصية هي حجر الزاوية في منصتنا، حيث نستخدم تقنيات تشفير متطورة لضمان بقاء كل ما يدور في الجلسة بينك وبين معالجك فقط.',
        'faq.q2': 'كيف أختار المعالج المناسب لي؟',
        'faq.a2': 'يمكنك تصفح الملفات الشخصية للمعالجين، والاطلاع على تخصصاتهم، وسنوات خبرتهم، ومنهجهم العلاجي لتختار من تشعر تجاهه بالارتياح النفسي.',
        'faq.q3': 'هل يمكنني إلغاء أو تغيير موعد جلستي؟',
        'faq.a3': 'نعم، نحن نتفهم حدوث تغييرات في المخططات. يمكنك إعادة جدولة جلستك أو إلغاؤها بكل سهولة عبر لوحة التحكم الخاصة بك وفقاً لسياسة الإلغاء المرنة لدينا.',
        'faq.q4': 'ما الفرق بين الاستشارة الفردية واستشارات الأزواج؟',
        'faq.a4': 'الاستشارة الفردية تركز على نموك الشخصي وتعاملك مع مشاعرك الخاصة، بينما تهدف استشارات الأزواج إلى تحسين التواصل وحل النزاعات وبناء علاقة أكثر قوة وتفاهماً بين الطرفين.',
        'about.ctaTitle': 'ابدأ رحلتك نحو السلام الداخلي اليوم',
        'about.ctaSubtitle': 'أنت تستحق أن تشعر بالتحسن. فريقنا من المختصين مستعد للاستماع إليك ومشاركتك الخطوة الأولى.',
        'about.ctaFind': 'ابحث عن طبيب',
        'about.ctaApply': 'انضم كطبيب',
        'doctor.forDoctorsTitle': 'انضم إلى مجتمع صابينا المهني',
        'doctor.forDoctorsSubtitle': 'هل أنت معالج نفسي مرخص تسعى لإحداث فرق حقيقي؟ انضم إلى "صابينا ثيرابي" لتوسيع نطاق وصولك المهني وتقديم خبراتك لمن يحتاجها في بيئة رقمية متطورة. نحن نوفر لك المنصة التي تعزز حضورك، وتمنحك الأدوات اللازمة لإدارة جلساتك بمرونة واحترافية، مع التركيز الكامل على جودة الرعاية التي تقدمها.',
        // Doctor Card/Profile
        'doctor.verified': 'معتمد',
    'doctor.responds': 'غالباً ما يرد خلال ساعتين',
    'doctor.price': 'السعر',
    'doctor.priceSuffix': ' / جلسة',
    'doctor.session': 'مدة الجلسة',
    'doctor.available': 'الموعد المتاح التالي',
    'doctor.book': 'حجز موعد',
    'doctor.viewProfile': 'عرض الملف الشخصي',
    'doctor.message': 'مراسلة الطبيب',
    'doctor.secure': 'دفع آمن • إلغاء حتى 24 ساعة قبل الموعد',
    'profile.about': 'حول',
    'profile.services': 'الخدمات',
    'profile.availability': 'المواعيد',
    'profile.reviews': 'التقييمات',
    'profile.methodology': 'منهجيتي في العلاج',
    'profile.experience': 'الخبرة المهنية',
    'profile.education': 'الخلفية الأكاديمية',
    'profile.insurance': 'التأمين والتغطية',
    'profile.insuranceDesc': 'د. سارة شريك معتمد مع كبرى شركات التأمين.',
    'profile.specializations': 'التخصصات السريرية',
    'profile.watchIntro': 'شاهد الفيديو التعريفي',
    'booking.quick': 'حجز سريع',
    'booking.service': 'الخدمة',
    'booking.date': 'التاريخ',
    'booking.time': 'المواعيد المتاحة',
    'booking.continue': 'المتابعة للحجز',
    'booking.similar': 'أطباء مشابهون',
    'footer.rights': '© 2026 صابينا ثيرابي. جميع الحقوق محفوظة.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('ar');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (key: string) => {
    return (translations[lang] as any)[key] || key;
  };

  const isRtl = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl }}>
      <div dir={isRtl ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
